// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"

	"github.com/google/wire"
	"github.com/imkarthi24/sf-backend/internal/app"
	"github.com/imkarthi24/sf-backend/internal/config"
	"github.com/imkarthi24/sf-backend/internal/cron"
	"github.com/imkarthi24/sf-backend/internal/handler"
	"github.com/imkarthi24/sf-backend/internal/handler/base"
	"github.com/imkarthi24/sf-backend/internal/log/newreliclog"
	"github.com/imkarthi24/sf-backend/internal/mapper"
	"github.com/imkarthi24/sf-backend/internal/repository"
	"github.com/imkarthi24/sf-backend/internal/router"
	"github.com/imkarthi24/sf-backend/internal/service"
	base2 "github.com/imkarthi24/sf-backend/internal/service/base"
	"github.com/loop-kar/pixie/db"
	service2 "github.com/loop-kar/pixie/service"
)

// Injectors from wire.go:

func InitApp(ctx *context.Context) (*app.App, error) {
	health := base.ProvideHealthHandler()
	appConfig, err := config.ProvideAppConfig()
	if err != nil {
		return nil, err
	}
	databaseConfig := appConfig.Database
	databaseConnectionParams := ProvideDatabaseConnectionParams(databaseConfig)
	gormDB, err := db.ProvideDatabase(databaseConnectionParams)
	if err != nil {
		return nil, err
	}
	dbTransactionManager := db.ProvideDBTransactionManager(gormDB)
	gormDAL := repository.ProvideGormDAL(dbTransactionManager)
	userRepository := repository.ProvideUserRepository(gormDAL)
	channelRepository := repository.ProvideChannelRepository(gormDAL)
	mapperMapper := mapper.ProvideMapper()
	responseMapper := mapper.ProvideResponseMapper()
	serviceService := ProvideServiceContainer(appConfig)
	emailService := serviceService.EmailService
	userService := service.ProvideUserService(userRepository, channelRepository, mapperMapper, appConfig, responseMapper, emailService)
	userHandler := handler.ProvideUserHandler(userService)
	channelService := service.ProvideChannelService(channelRepository, userRepository, mapperMapper, responseMapper)
	channelHandler := handler.ProvideChannelHandler(channelService)
	masterConfigRepository := repository.ProvideMasterConfigRepository(gormDAL)
	masterConfigService := service.ProvideMasterConfigService(masterConfigRepository, mapperMapper, appConfig, responseMapper)
	masterConfigHandler := handler.ProvideMasterConfigHandler(masterConfigService)
	adminRepository := repository.ProvideAdminRepository(gormDAL)
	adminService := service.ProvideAdminService(adminRepository)
	adminHandler := handler.ProvideAdminHandler(adminService)
	customerRepository := repository.ProvideCustomerRepository(gormDAL)
	personRepository := repository.ProvidePersonRepository(gormDAL)
	customerService := service.ProvideCustomerService(customerRepository, personRepository, mapperMapper, responseMapper)
	customerHandler := handler.ProvideCustomerHandler(customerService)
	enquiryRepository := repository.ProvideEnquiryRepository(gormDAL)
	enquiryService := service.ProvideEnquiryService(enquiryRepository, customerRepository, mapperMapper, responseMapper)
	enquiryHandler := handler.ProvideEnquiryHandler(enquiryService)
	orderRepository := repository.ProvideOrderRepository(gormDAL)
	orderHistoryRepository := repository.ProvideOrderHistoryRepository(gormDAL)
	orderService := service.ProvideOrderService(orderRepository, orderHistoryRepository, mapperMapper, responseMapper)
	orderHandler := handler.ProvideOrderHandler(orderService)
	orderItemRepository := repository.ProvideOrderItemRepository(gormDAL)
	orderItemService := service.ProvideOrderItemService(orderItemRepository, mapperMapper, responseMapper)
	orderItemHandler := handler.ProvideOrderItemHandler(orderItemService)
	measurementRepository := repository.ProvideMeasurementRepository(gormDAL)
	measurementHistoryRepository := repository.ProvideMeasurementHistoryRepository(gormDAL)
	measurementService := service.ProvideMeasurementService(measurementRepository, measurementHistoryRepository, mapperMapper, responseMapper)
	measurementHandler := handler.ProvideMeasurementHandler(measurementService)
	personService := service.ProvidePersonService(personRepository, mapperMapper, responseMapper)
	personHandler := handler.ProvidePersonHandler(personService)
	dressTypeRepository := repository.ProvideDressTypeRepository(gormDAL)
	dressTypeService := service.ProvideDressTypeService(dressTypeRepository, mapperMapper, responseMapper)
	dressTypeHandler := handler.ProvideDressTypeHandler(dressTypeService)
	orderHistoryService := service.ProvideOrderHistoryService(orderHistoryRepository, mapperMapper, responseMapper)
	orderHistoryHandler := handler.ProvideOrderHistoryHandler(orderHistoryService)
	measurementHistoryService := service.ProvideMeasurementHistoryService(measurementHistoryRepository, mapperMapper, responseMapper)
	measurementHistoryHandler := handler.ProvideMeasurementHistoryHandler(measurementHistoryService)
	enquiryHistoryRepository := repository.ProvideEnquiryHistoryRepository(gormDAL)
	enquiryHistoryService := service.ProvideEnquiryHistoryService(enquiryHistoryRepository, mapperMapper, responseMapper)
	enquiryHistoryHandler := handler.ProvideEnquiryHistoryHandler(enquiryHistoryService)
	expenseTrackerRepository := repository.ProvideExpenseTrackerRepository(gormDAL)
	expenseTrackerService := service.ProvideExpenseTrackerService(expenseTrackerRepository, mapperMapper, responseMapper)
	expenseTrackerHandler := handler.ProvideExpenseTrackerHandler(expenseTrackerService)
	taskRepository := repository.ProvideTaskRepository(gormDAL)
	taskService := service.ProvideTaskService(taskRepository, mapperMapper, responseMapper)
	taskHandler := handler.ProvideTaskHandler(taskService)
	baseHandler := base.ProvideBaseHandler(health, userHandler, channelHandler, masterConfigHandler, adminHandler, customerHandler, enquiryHandler, orderHandler, orderItemHandler, measurementHandler, personHandler, dressTypeHandler, orderHistoryHandler, measurementHistoryHandler, enquiryHistoryHandler, expenseTrackerHandler, taskHandler)
	serverConfig := appConfig.Server
	engine := router.InitRouter(baseHandler, serverConfig)
	application := newreliclog.ProvideNewRelic(appConfig)
	appApp := &app.App{
		Server:                 engine,
		AppConfig:              appConfig,
		StitchDB:               gormDB,
		NewRelic:               application,
		MasterConfigRepository: masterConfigRepository,
	}
	return appApp, nil
}

func InitJobService(ctx *context.Context) (*app.Task, error) {
	appConfig, err := config.ProvideAppConfig()
	if err != nil {
		return nil, err
	}
	databaseConfig := appConfig.Database
	databaseConnectionParams := ProvideDatabaseConnectionParams(databaseConfig)
	gormDB, err := db.ProvideDatabase(databaseConnectionParams)
	if err != nil {
		return nil, err
	}
	dbTransactionManager := db.ProvideDBTransactionManager(gormDB)
	gormDAL := repository.ProvideGormDAL(dbTransactionManager)
	userRepository := repository.ProvideUserRepository(gormDAL)
	channelRepository := repository.ProvideChannelRepository(gormDAL)
	mapperMapper := mapper.ProvideMapper()
	responseMapper := mapper.ProvideResponseMapper()
	serviceService := ProvideServiceContainer(appConfig)
	emailService := serviceService.EmailService
	userService := service.ProvideUserService(userRepository, channelRepository, mapperMapper, appConfig, responseMapper, emailService)
	notificationRepository := repository.ProvideNotificationRepository(gormDAL)
	smtpConfig := appConfig.SMTP
	notificationService := service.ProvideNotificationService(notificationRepository, mapperMapper, smtpConfig, emailService)
	channelService := service.ProvideChannelService(channelRepository, userRepository, mapperMapper, responseMapper)
	masterConfigRepository := repository.ProvideMasterConfigRepository(gormDAL)
	masterConfigService := service.ProvideMasterConfigService(masterConfigRepository, mapperMapper, appConfig, responseMapper)
	customerRepository := repository.ProvideCustomerRepository(gormDAL)
	personRepository := repository.ProvidePersonRepository(gormDAL)
	customerService := service.ProvideCustomerService(customerRepository, personRepository, mapperMapper, responseMapper)
	enquiryRepository := repository.ProvideEnquiryRepository(gormDAL)
	enquiryService := service.ProvideEnquiryService(enquiryRepository, customerRepository, mapperMapper, responseMapper)
	orderRepository := repository.ProvideOrderRepository(gormDAL)
	orderHistoryRepository := repository.ProvideOrderHistoryRepository(gormDAL)
	orderService := service.ProvideOrderService(orderRepository, orderHistoryRepository, mapperMapper, responseMapper)
	orderItemRepository := repository.ProvideOrderItemRepository(gormDAL)
	orderItemService := service.ProvideOrderItemService(orderItemRepository, mapperMapper, responseMapper)
	measurementRepository := repository.ProvideMeasurementRepository(gormDAL)
	measurementHistoryRepository := repository.ProvideMeasurementHistoryRepository(gormDAL)
	measurementService := service.ProvideMeasurementService(measurementRepository, measurementHistoryRepository, mapperMapper, responseMapper)
	personService := service.ProvidePersonService(personRepository, mapperMapper, responseMapper)
	dressTypeRepository := repository.ProvideDressTypeRepository(gormDAL)
	dressTypeService := service.ProvideDressTypeService(dressTypeRepository, mapperMapper, responseMapper)
	orderHistoryService := service.ProvideOrderHistoryService(orderHistoryRepository, mapperMapper, responseMapper)
	measurementHistoryService := service.ProvideMeasurementHistoryService(measurementHistoryRepository, mapperMapper, responseMapper)
	expenseTrackerRepository := repository.ProvideExpenseTrackerRepository(gormDAL)
	expenseTrackerService := service.ProvideExpenseTrackerService(expenseTrackerRepository, mapperMapper, responseMapper)
	taskRepository := repository.ProvideTaskRepository(gormDAL)
	taskService := service.ProvideTaskService(taskRepository, mapperMapper, responseMapper)
	baseService := base2.ProvideBaseService(userService, notificationService, channelService, masterConfigService, customerService, enquiryService, orderService, orderItemService, measurementService, personService, dressTypeService, orderHistoryService, measurementHistoryService, expenseTrackerService, taskService)
	application := newreliclog.ProvideNewRelic(appConfig)
	cronCron := cron.ProvideCron()
	task := &app.Task{
		ChitDb:      gormDB,
		BaseService: baseService,
		NewRelic:    application,
		Config:      appConfig,
		Cron:        cronCron,
	}
	return task, nil
}

// wire.go:

var appConfigSet = wire.NewSet(config.ProvideAppConfig, wire.FieldsOf(new(config.AppConfig), "SMTP", "Server", "Database"))

var pkgServiceSet = wire.NewSet(
	ProvideServiceContainer, wire.FieldsOf(new(*service2.Service), "EmailService"),
)

var handlerSet = wire.NewSet(base.ProvideHealthHandler, base.ProvideBaseHandler, handler.ProvideUserHandler, handler.ProvideChannelHandler, handler.ProvideMasterConfigHandler, handler.ProvideAdminHandler, handler.ProvideCustomerHandler, handler.ProvideEnquiryHandler, handler.ProvideOrderHandler, handler.ProvideOrderItemHandler, handler.ProvideMeasurementHandler, handler.ProvidePersonHandler, handler.ProvideDressTypeHandler, handler.ProvideOrderHistoryHandler, handler.ProvideMeasurementHistoryHandler, handler.ProvideEnquiryHistoryHandler, handler.ProvideExpenseTrackerHandler, handler.ProvideTaskHandler)

var logSet = wire.NewSet(newreliclog.ProvideNewRelic)

var routerSet = wire.NewSet(router.InitRouter)

var dbSet = wire.NewSet(
	ProvideDatabaseConnectionParams, db.ProvideDatabase, db.ProvideDBTransactionManager,
)

var mapperSet = wire.NewSet(mapper.ProvideMapper, mapper.ProvideResponseMapper)

var svcSet = wire.NewSet(service.ProvideUserService, service.ProvideNotificationService, service.ProvideChannelService, service.ProvideMasterConfigService, service.ProvideAdminService, service.ProvideCustomerService, service.ProvideEnquiryService, service.ProvideOrderService, service.ProvideOrderItemService, service.ProvideMeasurementService, service.ProvidePersonService, service.ProvideDressTypeService, service.ProvideOrderHistoryService, service.ProvideMeasurementHistoryService, service.ProvideEnquiryHistoryService, service.ProvideExpenseTrackerService, service.ProvideTaskService)

var baseSvc = wire.NewSet(base2.ProvideBaseService)

var repoSet = wire.NewSet(repository.ProvideGormDAL, repository.ProvideUserRepository, repository.ProvideNotificationRepository, repository.ProvideChannelRepository, repository.ProvideMasterConfigRepository, repository.ProvideAdminRepository, repository.ProvideCustomerRepository, repository.ProvideEnquiryRepository, repository.ProvideOrderRepository, repository.ProvideOrderItemRepository, repository.ProvideMeasurementRepository, repository.ProvidePersonRepository, repository.ProvideDressTypeRepository, repository.ProvideOrderHistoryRepository, repository.ProvideMeasurementHistoryRepository, repository.ProvideEnquiryHistoryRepository, repository.ProvideExpenseTrackerRepository, repository.ProvideTaskRepository)

var cronSet = wire.NewSet(cron.ProvideCron)
